### ISSUE TITLE
Wake on lan

### ISSUE THREAD

**Issue by XaXBullen** [RonnyWinkler/homey.qnap#1]
The wake on lan don’t work. Works fine in the wake on lan app in homey app Store.

**Comment by RonnyWinkler** [comment]
WoL is using the ethernet devices. Have you added your ethernet ports to homey after adding the QNAP NAS as device?
You can execute the WoL command for each ethernet device or the NAS itself. The NAS will call each ethenet device (added to Homey) to wake up.
So please check if you already added the ethernet port which should be used for WoL and try again. You can execute the command via flow (for the app with the selected NAS), or via maintenance menu in device settings for NAS and ethernet devices.
It would be nice if could comment if that was the reason. Thanks.

**Comment by XaXBullen** [comment]
> WoL is using the ethernet devices. Have you added your ethernet ports to homey after adding the QNAP NAS as device?
> You can execute the WoL command for each ethernet device or the NAS itself. The NAS will call each ethenet device (added to Homey) to wake up.
> So please check if you already added the ethernet port which should be used for WoL and try again. You can execute the command via flow (for the app with the selected NAS), or via maintenance menu in device settings for NAS and ethernet devices.
> It would be nice if could comment if that was the reason. Thanks.

My mistake! You have absolutely right! I did miss to add the Ethernet interface:) it is working fine! 😊

**Comment by RonnyWinkler** [comment]
Thanks for your answer. I will add some hints to the flow description in the next version to make a little clearer.
