### ISSUE TITLE
Add QNAP NAS with 404

### ISSUE THREAD

**Issue by miszterx** [RonnyWinkler/homey.qnap#3]
Hi,

I have tried to add a QNAP NAS item. It ask the hostname and port. It validate as valid. Then I add the credential and I got 404.

Homey app version: 1.0.12
QTS version: 5.0.1 2194

![IMG_7718](https://user-images.githubusercontent.com/56317037/198368194-0c93ffd7-2428-4f6d-97d1-010786e9e4b4.PNG)

Can you help me what is the issue here?

**Comment by RonnyWinkler** [comment]
Hi, can you please check if the port is correct? The NAS is using several ports. And the app can only check in the first step if the port is 'online', but not if it's the right one. You need the QTS port that you are using to login to your NAS in the browser with http. Not the port 80 that will be the webserver on your NAS by default.
The default QTS port should be 8080.

**Comment by miszterx** [comment]
Found it. The homey seems to be not using the internal DNS server.
With IP it worked fine. You can close the case.

**Comment by RonnyWinkler** [comment]
Thanks for the feedback. I'm glad it works :)
